name: flutter_date_interval
description: A package for configuring a repetition pattern, e.g. every other day, bi-weekly, monthly, etc. and finding dates that follow that pattern.
version: 2.1.2
homepage: https://github.com/andyhorn/flutter_date_interval

environment:
  sdk: ">=3.0.2 <4.0.0"
  flutter: ">=3.10.2"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

# The following section is specific to Flutter.
flutter:
