name: Bump version
on:
  push:
    branches:
      - master
jobs:
  bump:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.bump-version.outputs.tag }}
      type: ${{ steps.bump-version.outputs.release_type }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - name: GitHub Tag
        uses: mathieudutour/github-tag-action@v6.0
        id: bump-version
        with:
          github_token: ${{ secrets.PAT }}

  release:
    runs-on: ubuntu-latest
    needs: bump
    if: (needs.bump.outputs.type == 'patch') || (needs.bump.outputs.type == 'minor') || (needs.bump.outputs.type == 'major')
    steps:
      - uses: actions/checkout@v3
      - name: Create a Release
        uses: elgohr/Github-Release-Action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          title: ${{ needs.bump.outputs.tag }}
