name: Publish Package

env:
  FLUTTER_VERSION: "3.0.5"

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Flutter
        uses: britannio/action-install-flutter@v1
        with:
          version: $FLUTTER_VERSION
      - name: Install dependencies
        run: flutter pub get
      - name: Analyze
        run: flutter analyze
      - name: Run tests
        run: flutter test
      - name: Set Pub.dev Credentials
        uses: "andyhorn/set-pub-credentials"
        with:
          access-token: ${{ secrets.PUB_DEV_PUBLISH_ACCESS_TOKEN }}
          refresh-token: ${{ secrets.PUB_DEV_PUBLISH_REFRESH_TOKEN }}
          token-endpoint: ${{ secrets.PUB_DEV_PUBLISH_TOKEN_ENDPOINT }}
          expiration: ${{ secrets.PUB_DEV_PUBLISH_EXPIRATION }}
      - name: Check Publish Warnings
        run: pub publish --dry-run
      - name: Publish Package
        run: pub publish -f
